[WIP] Reinstanting RmqThreadCommunicator tests
aiidateam/kiwipy pull request #124
Opened 2022-10-13 18:37 UTC by muhrin

The release of kiwipy v0.8.0 made some breaking changes to the intended API of RmqThreadCommunicator.  I'm putting back tests that check for the intended API which will be fixed in due time.

2022-10-13 18:40 UTC, sphuber commented
Apologies captain, thanks for jumping in. Anyway had to quickly make a `0.8.1` to unpin some very strict dependency requirements

2022-10-13 18:49 UTC, muhrin commented
Nae dramas, I think it'll be a quick fix.

2022-10-20 08:50 UTC, muhrin commented
Ok.  I've fixed the problem.  Turned out to be an upstream bug in `pytray.LoopScheduler.`  Long story short, it was propagating a future the wrong way around: instead of the result from a thread future being passed to the asyncio future, it was doing the opposite.  Ultimately this meant that the `RmqIncomingTask.processing()` context would never have a value in the future it was waiting on, and therefore assume that the task should just be requeued.

All fixed in pytray 0.3.4.

2022-10-20 09:02 UTC, sphuber approved these changes
Thanks a lot @muhrin ! Just a few minor things to cleanup and then we can merge this.

2022-10-20 09:02 UTC, sphuber commented on src/kiwipy/rmq/threadcomms.py
> +        the task will be back in the queue"""
```suggestion
        """Requeue the task.
        
        This call is blocking and by the time function returns the task will be back in the queue.
        """
```

2022-10-20 09:02 UTC, sphuber commented on test/rmq/test_coroutine_communicator.py
> +    WARNING: This test mail fail when running with a debugger as it relies on the 'outcome'
```suggestion
    WARNING: This test may fail when running with a debugger as it relies on the 'outcome'
```

2022-10-20 09:03 UTC, sphuber requested changes
Minor changes

2022-10-20 09:22 UTC, sphuber approved these changes

2022-10-20 09:22 UTC, merged